version: "3"
services:
  app:
    build:
      args:
        user: javi
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: javi98/laravel-server-juegos-api:1.0.0
    container_name: laravel-server-juegos-api-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - ./docker-config/php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
    depends_on:
      - db

  db:
    image: mariadb:11.2.2
    container_name: laravel-server-juegos-api-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-config/mysql:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    container_name: laravel-server-juegos-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-config/nginx:/etc/nginx/conf.d

networks:
  laravel-server-juegos-api:
    driver: bridge

volumes:
  db-data: